![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [3]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

In [4]:
arr=np.zeros(9)

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [11]:
a = np.array([10, 20, 30, 40, 50])
print("Elementlar soni:", a.size)
print("Har bir element hajmi (bytes):", a.itemsize)
print("Jami xotira hajmi (bytes):", a.nbytes)

Elementlar soni: 5
Har bir element hajmi (bytes): 8
Jami xotira hajmi (bytes): 40


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [12]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [8]:
arr=np.zeros(12)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr=np.arange(20,60)
arr

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [17]:
arr=np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [18]:
arr=np.arange(12,21).reshape(3,3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [19]:
arr=np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [22]:
arr=np.random.random((2,2,2))
arr

array([[[0.97523915, 0.74395073],
        [0.27926581, 0.22566254]],

       [[0.89816109, 0.95354103],
        [0.49726183, 0.53035684]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [23]:
arr=np.random.random((9,9))
print(arr)
print(arr.min())
print(arr.max())

[[0.19004592 0.61123952 0.93594976 0.82857888 0.18624184 0.84202073
  0.16750592 0.63124225 0.49470043]
 [0.821556   0.16610063 0.14118242 0.65309938 0.70229723 0.84053687
  0.61847056 0.20826893 0.2980482 ]
 [0.97907585 0.6723298  0.86848701 0.95565219 0.09222166 0.87396946
  0.6069403  0.53074609 0.26524874]
 [0.65963532 0.06850537 0.71214058 0.0360757  0.89226591 0.08220041
  0.24443115 0.33266897 0.5006812 ]
 [0.46592762 0.36553415 0.5999532  0.2575447  0.01488572 0.17879908
  0.76935546 0.75009814 0.92623863]
 [0.42468082 0.28129461 0.19391512 0.55671399 0.55058964 0.10545671
  0.59081453 0.87707369 0.76440265]
 [0.71141608 0.12872351 0.27618526 0.25508542 0.85589597 0.65168168
  0.04960012 0.57864155 0.36925332]
 [0.1667896  0.56432433 0.51866426 0.28211017 0.02030522 0.07804753
  0.76721673 0.34316155 0.71381122]
 [0.26038893 0.84081264 0.37654796 0.15375086 0.94263717 0.90087806
  0.10543334 0.14341738 0.57210812]]
0.014885720795842383
0.9790758464343107


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [83]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [25]:
arr1=np.random.random((6,3))
arr2=np.random.random((3,4))
c=np.dot(arr1,arr2)
c

array([[0.60168035, 1.22927954, 0.68541877, 0.91818573],
       [0.61010787, 0.85506098, 0.3376479 , 1.04073568],
       [0.39701152, 0.76919987, 0.99579497, 0.94130092],
       [0.71889283, 1.01389961, 0.72888996, 1.40545604],
       [0.63859879, 1.25753353, 0.81196921, 1.05871495],
       [0.75783207, 1.1084348 , 0.90351601, 1.52554915]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))

9


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [27]:
arr1=np.array([4,7])
arr2=np.array([9,2])
print(arr1>arr2)
print(arr1>=arr2)
print(arr1<arr2)
print(arr1<=arr2)

[False  True]
[False  True]
[ True False]
[ True False]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipython-input-548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipython-input-548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [31]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,7])
np.intersect1d(arr1,arr2)

array([3, 4, 5])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [36]:
arr1=np.random.random((5))*10
print(arr1)
print(arr1%1)
print(np.floor(arr1))
print(arr1.astype(int))
print(np.trunc(arr1))

[3.51596479 8.92538159 7.49806972 1.7059903  6.48124013]
[0.51596479 0.92538159 0.49806972 0.7059903  0.48124013]
[3. 8. 7. 1. 6.]
[3 8 7 1 6]
[3. 8. 7. 1. 6.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [49]:
arr1=np.arange(9).reshape(3,3)
arr12=np.arange(3)
arr1[:,0]=arr12
arr1[:,1]=arr12
arr1[:,2]=arr12
arr1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [46]:
arr1=np.random.rand(10)
arr1.sort()
arr1

array([0.06341036, 0.08771404, 0.27111616, 0.31161366, 0.45003577,
       0.46619404, 0.60386026, 0.68034238, 0.79156837, 0.85838038])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [82]:
A=np.random.rand(10)
B=np.random.rand(10)
print(A)
print(B)
np.allclose(A,B)
np.array_equal(A,B)

[0.70937163 0.65564516 0.57320704 0.81563853 0.14501973 0.74040763
 0.75173838 0.64659767 0.80506889 0.45470654]
[0.36534729 0.37419041 0.35236228 0.18946397 0.30822897 0.49294152
 0.89580263 0.73114785 0.56667621 0.25988205]


False

#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [60]:
arr1=np.random.random((6,3))
arr2=np.random.random((3,4))
np.dot(arr1,arr2)

array([[0.45263874, 0.26208031, 0.33369679, 0.73853862],
       [0.39339577, 0.32567608, 0.52381289, 0.86430498],
       [0.23660079, 0.18491755, 0.32379608, 0.47965224],
       [0.38050701, 0.30449297, 0.5146884 , 0.79759922],
       [0.53355361, 0.39957147, 0.59886711, 1.08129144],
       [0.64277011, 0.36829933, 0.30601703, 1.10937738]])

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [58]:
arr1=np.random.rand(5)
print(arr1)
arr1[arr1.argmax()]=0
arr1

[0.64384335 0.21551749 0.68695999 0.87433878 0.03028307]


array([0.64384335, 0.21551749, 0.68695999, 0.        , 0.03028307])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [78]:
bugun  = np.datetime64('today')
kecha  = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')
print(bugun)
print(kecha)
print(ertaga)

2025-12-27
2025-12-26
2025-12-28


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [81]:
yanvar=np.arange('2016-01', '2016-02', dtype='datetime64[D]')
yanvar

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [86]:
arr1=np.random.random((5))*10
print(arr1)
print(arr1%1)
print(np.floor(arr1))
print(arr1.astype(int))
print(np.trunc(arr1))


[6.04212948 1.58801895 8.85229297 0.54945256 4.98253582]
[0.04212948 0.58801895 0.85229297 0.54945256 0.98253582]
[6. 1. 8. 0. 4.]
[6 1 8 0 4]
[6. 1. 8. 0. 4.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [87]:
arr1=np.random.rand(5)
arr2=np.random.rand(5)
np.add.reduce(arr1+arr2)


np.float64(4.874651561701227)

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [90]:
arr1=np.array([1,2,3,4,5])
arr1[::4]=0
arr1


array([0, 2, 3, 4, 0])

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`